//import ATTACK,RANGE_ATTACK,TOUGH,WORK,MOVE from 'constants';
import {ATTACK,RANGED_ATTACK,TOUGH,WORK,MOVE,HEAL,CARRY} from 'game/constants';

var Creep={
    CREEP_MEELE : [ATTACK,ATTACK,MOVE,MOVE],
    CREEP_RANGED : [RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE],
    CREEP_HEALER : [HEAL,HEAL,MOVE,MOVE],
    CREEP_HEAVY_MEELE : [TOUGH,TOUGH,TOUGH,TOUGH,ATTACK,ATTACK,ATTACK,ATTACK,MOVE,MOVE,MOVE,MOVE],
    CREEP_WORK : [WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
    CREEP_HEAVY_WORK : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE]
}

export default Creep;